name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: cp .example.env .env
      - run: pnpm build
      - run: pnpm zip
      - uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-dist
          path: |
            dist/
            dist-zip/